<?php

use Drupal\Core\Form\FormStateInterface;
function views_tags_filters_form_alter(&$form, FormStateInterface $form_state) {
  /**
   * Apply the form_alter to a specific form #id
   * the form #id can be found through inspecting the markup
   */
//  var_dump($form);
//  exit();
  if($form['#id'] == 'views-exposed-form-gallery-page-1') {
    /**
     * Include a js and css, which was defined in popolo_custom.libraries.yml
     */
    $form['#attached']['library'][] = 'views_tags_filters/views_tags_filters.enable';
    $form['#attached']['library'][] = 'views_tags_filters/views_tags_filters.forms';
    /**
     * Extract the options from the Views Exposed Filter <select>-list
     */
    $links = $form['field_gallery_type_target_id']['#options'];
    /**
     * Iterate over the options ($links) to build an array ($pop_array) of links
     */
    $i = 0; // Initiate counter/index
    $pop_array = array();
    foreach ($links as $tid => $term_name) {
      if ($tid == 'All') {
        $pop_array[$i]['#markup'] = '<span class="filter-tab"><a href="" class="active" id="' .$tid . '">' . $term_name . '</a></span>';
      }
      else {
        $pop_array[$i]['#markup'] = '<span class="filter-tab"><a href="" id="' .$tid . '">' . $term_name . '</a></span>';
      }
      $i++; // Increase counter/index
    }
    /**
     * Create the item-list the form should render
     */
    $form['links'] = [
      '#theme' => 'item_list',
      '#items' => $pop_array,
      '#attributes' => array('class' => array('pop-list')),
    ];
  }

  else {
    //nothing...
  }
}
